require 'gosu'
require_relative 'window'
require_relative 'quadro'
require_relative 'caja1'
require_relative 'biceps1'
require_relative 'tunel1'
require_relative 'tatica1'
require_relative 'pe1'
require_relative 'parabens1'
require_relative 'torax1'
require_relative 'cafe1'
require_relative 'amaveis1'
require_relative 'carater1'
require_relative 'so1'
require_relative 'cipo1'
require_relative 'ion1'
require_relative 'cha1'
require_relative 'taxi1'
require_relative 'bonus1'
require_relative 'CampoA'
require_relative 'CampoB'
require_relative 'CampoC'
require_relative 'CampoD'
require_relative 'CampoE'
require_relative 'CampoF'
require_relative 'CampoG'
require_relative 'CampoH'
require_relative 'CampoI'
require_relative 'CampoJ'
require_relative 'CampoK'
require_relative 'CampoL1'
require_relative 'CampoM'
require_relative 'CampoN1'
require_relative 'CampoO'
require_relative 'AsMono'
require_relative 'EsMono'
require_relative 'OsMono'
require_relative 'As'
require_relative 'Es'
require_relative 'Os'
require_relative 'EMoxi'
require_relative 'PS'
require_relative 'R'
require_relative 'X'
require_relative 'N'
require_relative 'L'
require_relative 'UM'
require_relative 'IS'
require_relative 'DITONGO'
require_relative 'PAROX'
require_relative 'MONOX'
require_relative 'OXIT'
require_relative 'CampoP'
require_relative 'PARO'
require_relative 'PROPAROX'
require_relative 'CURSOR'



window = Window.new
window.show

